const ChapterProgress = [
  { childId: "Z2z0fPcNeP", ChapterId: "PFFIOYZDii", progress: 50 },
  { childId: "Z2z0fPcNeP", ChapterId: "JBxaXh8ZZ5", progress: 70 },
  { childId: "Z2z0fPcNeP", ChapterId: "za4_bX9iVK", progress: 20 },
  { childId: "Z2z0fPcNeP", ChapterId: "v2JuuxbTD0", progress: 25 },
  { childId: "Z2z0fPcNeP", ChapterId: "JBxaXh8ZZ52a", progress: 80 },
  { childId: "Z2z0fPcNeP", ChapterId: "lbdt7GGI96", progress: 80 },
  { childId: "Z2z0fPcNeP", ChapterId: "gMWne4bwD4", progress: 50 },
  { childId: "Z2z0fPcNeP", ChapterId: "PFFIOYZDii1c", progress: 100 },
  { childId: "Z2z0fPcNeP", ChapterId: "5syTRIJIOC5b", progress: 22 },
  { childId: "Z2z0fPcNeP", ChapterId: "PFFIOYZDii1a", progress: 15 },
  { childId: "Z2z0fPcNeP", ChapterId: "JBxaXh8ZZ52a", progress: 66 },
  { childId: "Z2z0fPcNeP", ChapterId: "za4_bX9iVK2a", progress: 85 },
  { childId: "Z2z0fPcNeP", ChapterId: "PFFIOYZDii1b", progress: 90 },
  { childId: "Z2z0fPcNeP", ChapterId: "QePe086yyWD1", progress: 20 },
  { childId: "Z2z0fPcNeP", ChapterId: "U3yoHdArxjD2", progress: 45 },
  { childId: "Z2z0fPcNeP", ChapterId: "-y76EaIGn2xD3", progress: 95 },
  { childId: "Z2z0fPcNeP", ChapterId: "PFFIOYZDii1", progress: 100 },
  { childId: "Z2z0fPcNeP", ChapterId: "JBxaXh8ZZ52", progress: 80 },
  { childId: "Z2z0fPcNeP", ChapterId: "za4_bX9iVK2", progress: 45 },
  { childId: "Z2z0fPcNeP", ChapterId: "5syTRIJIOC4", progress: 100 },
  { childId: "Z2z0fPcNeP", ChapterId: "B_d74PPDrh", progress: 99 },
  //
  { childId: "RTWxmsj2MY", ChapterId: "3S-Yb5_QMY", progress: 20 },
  { childId: "RTWxmsj2MY", ChapterId: "IWl1j7vaVT", progress: 35 },
  { childId: "RTWxmsj2MY", ChapterId: "-V06yDnOIp", progress: 70 },
  { childId: "RTWxmsj2MY", ChapterId: "UQ7F92N3EB", progress: 70 },
  { childId: "RTWxmsj2MY", ChapterId: "B_d74PPDrh", progress: 99 },
  { childId: "RTWxmsj2MY", ChapterId: "v2JuuxbTD0", progress: 34 },
  { childId: "RTWxmsj2MY", ChapterId: "MhLJXuEHgX", progress: 23 },
  { childId: "RTWxmsj2MY", ChapterId: "4H5952slQA", progress: 56 },
  { childId: "RTWxmsj2MY", ChapterId: "QePe086yyW2", progress: 77 },
  { childId: "RTWxmsj2MY", ChapterId: "U3yoHdArxj3", progress: 45 },
  { childId: "RTWxmsj2MY", ChapterId: "QePe086yyWD1", progress: 15 },
  { childId: "RTWxmsj2MY", ChapterId: "U3yoHdArxjD2", progress: 78 },
  { childId: "RTWxmsj2MY", ChapterId: "-y76EaIGn2xD4", progress: 87 },
  { childId: "RTWxmsj2MY", ChapterId: "PFFIOYZDii1a", progress: 89 },
  { childId: "RTWxmsj2MY", ChapterId: "JBxaXh8ZZ52a", progress: 66 },
  { childId: "RTWxmsj2MY", ChapterId: "za4_bX9iVK2a", progress: 50 },
  { childId: "RTWxmsj2MY", ChapterId: "29Ff0ntsy57b", progress: 70 },
  { childId: "RTWxmsj2MY", ChapterId: "PFFIOYZDii1b", progress: 70 },
  //
  { childId: "h3D4SoYjsF", ChapterId: "v2JuuxbTD0", progress: 100 },
  { childId: "h3D4SoYjsF", ChapterId: "MhLJXuEHgX", progress: 80 },
  { childId: "h3D4SoYjsF", ChapterId: "4H5952slQA", progress: 90 },
  { childId: "h3D4SoYjsF", ChapterId: "Fp4vr3Z1L1", progress: 99 },
  { childId: "h3D4SoYjsF", ChapterId: "IWl1j7vaVT", progress: 88 },
  { childId: "h3D4SoYjsF", ChapterId: "QePe086yyW2", progress: 65 },
  { childId: "h3D4SoYjsF", ChapterId: "U3yoHdArxj3", progress: 45 },
  { childId: "h3D4SoYjsF", ChapterId: "-y76EaIGn2x4", progress: 49 },
  { childId: "h3D4SoYjsF", ChapterId: "QePe086yyWD1", progress: 59 },
  { childId: "h3D4SoYjsF", ChapterId: "U3yoHdArxjD2", progress: 20 },
  { childId: "h3D4SoYjsF", ChapterId: "-y76EaIGn2xD3", progress: 100 },
  { childId: "h3D4SoYjsF", ChapterId: "PFFIOYZDii1b", progress: 100 },
  { childId: "h3D4SoYjsF", ChapterId: "JBxaXh8ZZ52b", progress: 76 },
  { childId: "h3D4SoYjsF", ChapterId: "za4_bX9iVK3b", progress: 100 },
];

export default ChapterProgress;
