const Sections = [
  {
    id: "CAV5Zd1cxF",
    title: "Informatique",
    children: ["Z2z0fPcNeP"],
    subjects: [
      "wmgtiW-C4z",
      "nfvzD9Gg2z",
      "pJsujiSMdB",
      "HenYTU1UIU",
      "FOoQ3Vjxnl",
      "wmgtiW-C4z1",
      "2hQMRz_tE_8",
      "wmgtiW-C4z5",
      "2hQMRz_tE_1",
      "wmgtiW-C4zz1",
      "wmgtiW-C4zz2",
      "wmgtiW-C4zz3",
    ],
    // sessions: [{}],
  },
  {
    id: "GEbB8YiRJS",
    title: "Math",
    children: ["RTWxmsj2MY"],
    subjects: [
      "nfvzD9Gg2z",
      "pJsujiSMdB",
      "HenYTU1UIU",
      "FOoQ3Vjxnl",
      "2hQMRz_tE_8",
      "wmgtiW-C4z5",
      "2hQMRz_tE_1",
      "wmgtiW-C4zz1",
      "wmgtiW-C4zz2",
      "wmgtiW-C4zz3",
    ],
    // sessions: [{}],
  },
  {
    id: "7AD5I1fnra",
    title: "Letter",
    children: ["h3D4SoYjsF"],
    subjects: [
      "FOoQ3Vjxnl",
      "wmgtiW-C4zz2",
      "2hQMRz_tE_8",
      "2hQMRz_tE_1",
      "nfvzD9Gg2z",
    ],
    // sessions: [{}],
  },
];
export default Sections;
