const Sessions = [
  {
    id: "-FgvD-SUVA",
    subject: "Anglais",
    date: new Date(Date.now()).toString(),
    title: "Anglais-Unit4-Life",
    time: "90:00",
    prof: "Haythem",
  },
  {
    id: "frUfDwNkS6",
    subject: "Informatique",
    date: new Date(Date.now()).toString(),
    title: "Programmation",
    time: "90:00",
    prof: "Hazem",
  },
  {
    id: "rY0PBr14_i",
    subject: "Physique",
    date: "2022-4-01T15:00:00",
    title: "Physique ( Excellent )Série 35",
    time: "90:00",
    prof: "Adem",
  },
  {
    id: "JcJbxkG5eo",
    subject: "Math",
    date: new Date(Date.now()).toString(),
    title: "Maths-St-fonction ",
    time: "90:00",
    prof: "mohamed",
  },
  {
    id: "l36ReUJBoB",
    subject: "Arabe",
    date: "2022-07-20T08:00:00",
    title: "عربيّة",
    time: "90:00",
    prof: "riadh",
  },
  {
    id: "ybxlllavUB",
    subject: "Anglais",
    date: new Date(Date.now()).toString(),
    title: "Anglais ",
    time: "90:00",
    prof: "Ilhem",
  },
  {
    id: "ybxlllavUB1",
    subject: "Anglais",
    date: "2022-04-22T14:30:00",
    title: "Tic",
    time: "90:00",
    prof: "Ilhem",
  },
  {
    id: "ybxlllavUB45",
    subject: "Tic",
    date: "2022-04-22T15:00:00",
    title: "Tic",
    time: "90:00",
    prof: "Ilhem",
  },
  {
    id: "ybxlllavUB2",
    subject: "Anglais",
    date: "2022-04-30T19:45:00",
    title: "Anglais",
    time: "90:00",
    prof: "Ilhem",
  },
  {
    id: "ybxlllavUB4",
    subject: "Programmation",
    date: "2022-04-11T21:45:00",
    title: "Anglais",
    time: "90:00",
    prof: "Ilhem",
  },
  {
    id: "ybxlllavUB9",
    subject: "Programmation",
    date: "2022-04-11T15:45:00",
    title: "Anglais",
    time: "90:00",
    prof: "Ilhem",
  },
  {
    id: "ybxlllavUB12",
    subject: "Programmation",
    date: "2022-04-10T16:30:00",
    title: "Anglais",
    time: "90:00",
    prof: "Ilhem",
  },
  {
    id: "ybxlllavUB13",
    subject: "عربية",
    date: "2022-04-10T17:45:00",
    title: "عربية",
    time: "90:00",
    prof: "Ilhem",
  },
  {
    id: "ybxlllavUB14",
    subject: "فلسفة",
    date: "2022-04-10T17:15:00",
    title: "Anglais",
    time: "90:00",
    prof: "Ilhem",
  },
];

export default Sessions;
